plugins:
  sl:
    executor: central_deployment_agent
    package_name: cloudify-serverless-plugin
    package_version: 0.1.3
data_types:
  cloudify.types.serverless.ServerlessConfig:
    properties:
      executable_path:
        type: string
        default: ''
  cloudify.types.serverless.ClientConfig:
    properties:
      provider:
        type: string
        required: false
      credentials:
        type: dict
        required: false
  cloudify.types.serverless.ServiceConfig:
    properties:
      name:
        type: string
        required: true
      template:
        type: string
        required: true
      template_url:
        type: string
        required: false
      template_path:
        type: string
        required: false
      functions:
        type: list
        required: true
      env:
        type: dict
        required: false
  cloudify.types.serverless.FunctionConfig:
    properties:
      name:
        type: string
        required: true
      handler:
        type: string
        required: true
      events:
        type: list
        required: false
      environment:
        type: dict
        required: false
dsl_definitions:
  serverless_configuration:
    serverless_config: &id001
      type: cloudify.types.serverless.ServerlessConfig
  use_external_resource_desc: >
    Indicate whether the resource exists or if Cloudify should create the resource, true if you are bringing an existing resource, false if you want cloudify to create it.
  external_resource:
    use_external_resource: &id002
      type: boolean
      default: false
node_types:
  cloudify.nodes.serverless.Binary:
    derived_from: cloudify.nodes.SoftwareComponent
    properties:
      serverless_config: *id001
      use_external_resource: *id002
      installation_source:
        type: string
        default: https://github.com/serverless/serverless/releases/download/v3.22.0/serverless-linux-x64
      max_sleep_time:
        type: integer
        default: 300
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: sl.serverless_plugin.tasks.install_binary
        delete:
          implementation: sl.serverless_plugin.tasks.uninstall_binary
  cloudify.nodes.serverless.Service:
    derived_from: cloudify.nodes.SoftwareComponent
    properties:
      serverless_config: *id001
      use_external_resource: *id002
      client_config:
        type: cloudify.types.serverless.ClientConfig
        required: true
      resource_config:
        type: cloudify.types.serverless.ServiceConfig
        required: true
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: sl.serverless_plugin.tasks.create
        configure:
          implementation: sl.serverless_plugin.tasks.configure
        start:
          implementation: sl.serverless_plugin.tasks.start
        poststart:
          implementation: sl.serverless_plugin.tasks.poststart
        stop:
          implementation: sl.serverless_plugin.tasks.stop
        delete:
          implementation: sl.serverless_plugin.tasks.delete
      serverless.interface:
        invoke:
          implementation: sl.serverless_plugin.tasks.invoke
          inputs:
            functions:
              default: []
        metrics:
          implementation: sl.serverless_plugin.tasks.metrics
          inputs:
            functions:
              default: []
