plugins:

  serverless:
    executor: central_deployment_agent
    source: https://github.com/mabuaisha/cloudify-serverless-plugin/archive/0.1.zip
    package_name: cloudify-serverless-plugin
    package_version: '0.1'

data_types:
  cloudify.types.serverless.BaseConfig:
    properties:
      provider:
        type: string
        description: The Serverless provider name.
        required: false
      config:
        description: Credentials of the provider.
        required: false
        type: dict

  cloudify.types.serverless.ServiceConfig:
    properties:
      name:
        type: string
        description: The Serverless service name.
        required: true
      template:
        type: string
        description: Template for the service.
        required: true
      template_url:
        type: string
        description: Template URL for the service. Supports GitHub, BitBucket.
        required: false
      template_path:
        type: string
        description: Template local path for the service.
        required: false
      path:
        type: string
        description: The path where the service should be created.
        required: false

  cloudify.types.serverless.FunctionConfig:
    properties:
      name:
        type: string
        description: The Serverless function name.
        required: true
      handler:
        type: string
        description: The Serverless function handelr.
        required: true
      events:
        type: list
        description: List of events assoicated with the function.
        required: false
      environment:
        type: dict
        description: Function environment variables.
        required: false


node_types:
  cloudify.nodes.serverless.Service:
    derived_from: cloudify.nodes.SoftwareComponent
    properties:
      provider_config:
        type: cloudify.types.serverless.BaseConfig
        required: true
        description: Provider Config
      service_config:
        type: cloudify.types.serverless.ServiceConfig
        required: true
        description: Path to the service file
      functions:
        type: list
        required: true
        description: List of function that need to define
      executable_path:
        type: string
        description: The path to the serverless binary executable.
        default: /usr/bin/serverless
      variables:
        type: dict
        description: Set of variables to use for functions
        required: false
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: serverless.serverless_plugin.tasks.create
        configure:
          implementation: serverless.serverless_plugin.tasks.configure
        start:
          implementation: serverless.serverless_plugin.tasks.start
        delete:
          implementation: serverless.serverless_plugin.tasks.delete