plugins:

  serverless:
    executor: central_deployment_agent
    source: https://github.com/mabuaisha/cloudify-serverless-plugin/archive/0.1.zip
    package_name: cloudify-openstack-plugin
    package_version: '0.1'