version: 2.1

orbs:
  node: cloudify/unittest-orb@1.0 #orb version
  wagonorb: cloudify/wagon-bulder-orb@2.5 #orb version
  releaseorb: cloudify/release-orb@1.4 #orb version
  managerorb: cloudify/manager-orb@2.0

checkout:
  post:
    - >
      if [ -n "$CI_PULL_REQUEST" ]; then
        PR_ID=${CI_PULL_REQUEST##*/}
        git fetch origin +refs/pull/$PR_ID/merge:
        git checkout -qf FETCH_HEAD
        git submodule update --init --recursive
      fi

executors:

  py36:
    docker:
      - image: circleci/python:3.6

  cloudify-machine-py3:
    machine:
      image: ubuntu-2004:202201-02

commands:
  prepare_test_manager:
    steps:
      - run: ecosystem-test prepare-test-manager -l $TEST_LICENSE -es aws_access_key_id=$aws_access_key_id -es aws_secret_access_key=$aws_secret_access_key --bundle-path workspace/build/cloudify-plugins-bundle.tgz --yum-package python-netaddr --yum-package git -p $(find ~/project/workspace/build/ -name *centos-Core*x86_64.wgn)  ~/project/plugin.yaml

  run_blueprint:
    steps:
      - run: ecosystem-test local-blueprint-test -b examples/blueprint.yaml --test-id=hello-world-example --on-failure=uninstall-force --timeout=1800

jobs:

  integration_tests_py3:
    executor: cloudify-machine-py3
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
    steps:
      - checkout
      - managerorb/create_manager_container_latest
      - prepare_test_manager
      - run_blueprint

workflows:
  version: 2
  tests:
    jobs:
      - node/check_py3_compat_job
      - node/unittests_job
      - node/validate_version_job
      - node/validate_documentation_job
      - wagonorb/wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master)/
      - wagonorb/arch64_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - wagonorb/rhel_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master)/
      - wagonorb/build_bundle:
          filters:
            branches:
              only: /([0-9\.]*\-build|master)/
          requires:
            - wagonorb/wagon
            - wagonorb/arch64_wagon
            - wagonorb/rhel_wagon
      - integration_tests_py3:
          requires:
            - wagonorb/wagon
            - wagonorb/arch64_wagon
            - wagonorb/rhel_wagon
            - wagonorb/build_bundle
          filters:
            branches:
              only: /([0-9\.]*\-build|master)/
      - releaseorb/release:
          filters:
            branches:
              only: /master/
          requires:
            - wagonorb/wagon
            - wagonorb/arch64_wagon
            - wagonorb/rhel_wagon
            - wagonorb/build_bundle
            - node/validate_version_job
            - node/validate_documentation_job
            - integration_tests_py3
      - releaseorb/merge_docs_job:
          filters:
            branches:
              only: /master/
          requires:
            - releaseorb/release
            - node/validate_documentation_job
  nightly:
    triggers:
    - schedule:
        cron: "0 1 * * 0,1,3,5"
        filters:
          branches:
            only:
              - master
    jobs:
      - node/check_py3_compat_job
      - node/validate_version_job
      - node/unittests_job
      - wagonorb/wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master)/
      - wagonorb/arch64_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - wagonorb/rhel_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master)/
      - wagonorb/build_bundle:
          filters:
            branches:
              only: /master/
          requires:
            - wagonorb/wagon
            - wagonorb/arch64_wagon
            - wagonorb/rhel_wagon
      - integration_tests_py3:
          requires:
            - wagonorb/build_bundle
            - wagonorb/wagon
            - wagonorb/arch64_wagon
            - wagonorb/rhel_wagon
          filters:
            branches:
              only: /([0-9\.]*\-build|master)/
